services:
  # Serveur RabbitMQ
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-server
    ports:
      - "5672:5672" # AMQP port
      - "15672:15672" # Management UI port
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - rabbitmq_network
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Serveur Web (Interface utilisateur)
  web-server:
    build: .
    container_name: rabbitmq-web-server
    ports:
      - "3000:3000"
    environment:
      - RABBITMQ_URL=amqp://user:password@rabbitmq:5672
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - rabbitmq_network
    command: ["node", "src/web-server.js"]
    restart: unless-stopped

  # Worker Addition
  worker-add:
    build: .
    container_name: rabbitmq-worker-add
    environment:
      - RABBITMQ_URL=amqp://user:password@rabbitmq:5672
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - rabbitmq_network
    command: ["node", "src/worker.js", "add"]
    restart: unless-stopped

  # Worker Soustraction
  worker-sub:
    build: .
    container_name: rabbitmq-worker-sub
    environment:
      - RABBITMQ_URL=amqp://user:password@rabbitmq:5672
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - rabbitmq_network
    command: ["node", "src/worker.js", "sub"]
    restart: unless-stopped

  # Worker Multiplication
  worker-mul:
    build: .
    container_name: rabbitmq-worker-mul
    environment:
      - RABBITMQ_URL=amqp://user:password@rabbitmq:5672
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - rabbitmq_network
    command: ["node", "src/worker.js", "mul"]
    restart: unless-stopped

  # Worker Division
  worker-div:
    build: .
    container_name: rabbitmq-worker-div
    environment:
      - RABBITMQ_URL=amqp://user:password@rabbitmq:5672
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - rabbitmq_network
    command: ["node", "src/worker.js", "div"]
    restart: unless-stopped

volumes:
  rabbitmq_data:
    driver: local

networks:
  rabbitmq_network:
    driver: bridge
